### ISSUE TITLE
not sure how to run the program

### ISSUE THREAD

**Issue by pdinc-oss** [dehasi/groovy-dc#3]
I read https://compscicenter.ru/media/project_presentations/2016-spring/18.%20%D0%93%D0%B0%D0%BB%D0%B5%D0%B5%D0%B2.pdf but it is not clear on how to use groovy-dc

**Comment by opticyclic** [comment]
There are only tests and not main methods.
If you add the following to the Deompiler class you can get it to run:

    public static void main(String[] args) throws IOException {
        Decompiler decompiler = new Decompiler();
        Loader loader = new Loader();
        String path = args[0];

        ClassReader classReader = loader.loadFromFileSystem(path);
        String content = decompiler.decompile(classReader).toString();

        System.out.println(content);
    }

However, it expects classes to be on the file system in `build/classes/main/<package>` and not in a jar.

Also, once you do run it you will find that it doesn't actually decompile the body of a class.
See https://github.com/dehasi/groovy-dc/blob/1c8d244be3b0130df69b7f0d892e5eea0a38f69f/src/main/java/decompiler/utils/CVisitorUtils.java#L130-L131 

This means that it is only in the initial phase and not a complete decompiler that can actually be used right now.

**Comment by dehasi** [comment]
Thank you for the question.
I didn't even think that somebody will use my code :) 
It was just my student project.  I've updated the readme. Hope it helps to avoid misleading it the future.

**Comment by syepes** [comment]
@dehasi 

Interesting project, it would be great to have a simpler runner. I still have not managed to make it work :-(

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at decompiler.utils.ParserUtils.parsePackagaName(ParserUtils.java:65)
	at decompiler.visitors.CVisitor.visit(CVisitor.java:64)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:492)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:355)
	at decompiler.Decompiler.decompile(Decompiler.java:12)
	at decompiler.Decompiler$decompile.call(Unknown Source)
	at ConsoleScript13.run(ConsoleScript13:17)
```

**Comment by dehasi** [comment]
Hi @syepes to be honest, I'm surprised that somebody still is interested in the project:)
I'll try to add a runner and update the readme next week. Or you can make a PR on your own ;)
